service:
  name: "employeeRegistration"

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom:
  webpack:
      webpackConfig: ./webpack.config.js
      includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true      

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1

functions:
  CreateEmployer:
    handler: src/functions/CreateEmployer.handle     
    events:
      - http:
          path: /createEmployer
          method: POST
          cors: true

resources:
  Resources:
    dbEmployee:
      Type: AWS::DynamoDB::Table      
      Properties:
        TableName: Employeers
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH                        

